# Generated by Django 3.1.3 on 2020-11-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='detalle',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='detpo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='persona',
            name='mail',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
